openapi: '3.0.2'
info:
  description: Simple to-do list application
  version: '1.0'
  title: To-Do List
servers:
  - url: https://localhost:3000

components:
  schemas:
    Item:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        body:
          type: "string"
paths:
  /list:
    get:
      tags:
      - "list"
      description: get all list items
      operationId: "getList"
      responses:
        '200':
          description: OK
        '404':
          description: "Not Found"
  /listItem:
    post:
     tags:
      - "listItem"
     description: posts item to list
     parameters:
     - in: "path"
       name: "body"
       description: "Item object that needs to be added to list"
       required: true
       schema:
         type: "string"
         $ref: "#/components/schemas/Item"
     responses:
      '201':
        description: OK
      '405':
        description: "Invalid Input"
  /listItem/{id}:
    get:
      tags:
      - "listItem/{id}"
      description: get list item by id
      parameters:
      - in: "path"
        required: true
        schema:
          type: "integer"
        name: "id"
      responses:
        '200':
          description: OK
        '404':
          description: "Not Found"
        '405':
          description: "Invalid Input"
    patch:
      tags:
      - "listItem/{id}"
      description: edit a list item found by id
      parameters:
      - in: "path"
        name: "id"
        required: true
        schema:
          type: "integer"
          $ref: "#/components/schemas/Item"
      responses:
        '200':
          description: OK
        '404':
          description: "Not Found"
        '405':
          description: "Invalid Input"
    delete:
      tags:
      - "listItem/{id}"
      description: delete a list item found by id
      parameters:
      - in: "path"
        required: true
        schema:
          type: "integer"
        name: "id"
      responses:
        '200':
          description: OK
        '404':
          description: "Not Found"

